# -*- coding: utf-8 -*-
"""prompt_template

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHxb0ir2GG-S98ks7g_aDMUnCVQkGd0S
"""

import os
os.environ["GROQ_API_KEY"]='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'
!pip install langchain --upgrade

!pip install langchain_community

!pip install -q groq


from langchain import PromptTemplate
from langchain.chains import LLMChain


from langchain.chat_models import ChatOpenAI

from groq import Groq

prompt="I want you to act as an expert on {financial_concept}. "
"Please provide a concise and informative explanation of {financial_concept} "
"for a general audience."

prompt
from langchain.llms import OpenAI

prompt_template=PromptTemplate(
    input_variables=['financial_concept'],
    template=prompt,
)

tp=prompt_template.format(financial_concept='incometax')
llm = ChatOpenAI(
        openai_api_base="https://api.groq.com/openai/v1",
        openai_api_key=os.environ['GROQ_API_KEY'],
        model_name='llama-3.2-1b-preview',
        temperature=0,
        max_tokens=1000,
    )

llm

chain = LLMChain(prompt=prompt_template,llm=llm)



chain.run('data science ')

prompt1="in an essay  Translate the following sentence  {sentence} into {target_language}"

Prompt_Template1=PromptTemplate(input_variables=['sentence','target_language'],template=prompt1)

llm1=ChatOpenAI(openai_api_base='https://api.groq.com/openai/v1',
                openai_api_key=os.environ['GROQ_API_KEY'],
                temperature=0,
                model_name='llama-3.2-3b-preview',
                max_tokens=1000)

chain1=LLMChain(prompt=Prompt_Template1,llm=llm1)

chain1.run({'sentence':'This is Avinash','target_language':'hindi'})

prompt3="This is avinash working in {sentence} my {sentence2} is 17 lakhs"
"explain to me about {sentence} and {sentence2} to general audience"

prompt3.format(sentence='amazon',sentence2='salary')

prompt_template1=PromptTemplate(input_variables=['sentence','sentenc2'],template=prompt3)

llm3=ChatOpenAI(openai_api_base="https://api.groq.com/openai/v1",
                openai_api_key=os.environ['GROQ_API_KEY'],
                model_name='llama-3.2-3b-preview',
                max_tokens=1000)

chat=LLMChain(prompt=prompt_template1,llm=llm3)

chat.run({'sentence':'amazon','sentence2':'salary'})

# language translation
prompt4 ="he is doing {sentence} to {sentence1}"
"translate {sentence} to {sentence1} for general audience "

prompt_template2=PromptTemplate(input_variables=['sentence','sentence1'],template=prompt4)

llm4=ChatOpenAI(openai_api_base="https://api.groq.com/openai/v1",
                openai_api_key=os.environ['GROQ_API_KEY'],
                model_name='llama-3.2-3b-preview',
                temperature=0.3)

LLMChain(prompt=prompt_template2,llm=llm4)({'sentence':'practice makes man perfect','sentence1':'telugu'})